### ISSUE TITLE
Allow planner system copying to temp folder

### ISSUE THREAD

**Issue by ssardina** [lslll0302/Eval-of-FOND-planners-#11]
Some planners will produce temporary files and if we ran more than 1 at the same time, they may collude.

So, the planner class can have a variable `needs_clone` which means that this planner needs to be cloned to a `/tmp` location, run, used and then deleted, for each instance.

The planner class then also needs the directory of the planner so that the script can clone the whole planner.

**Comment by lslll0302** [comment]
done
