### ISSUE TITLE
Restructure repo

### ISSUE THREAD

**Issue by ssardina** [lslll0302/Eval-of-FOND-planners-#5]
The repo should have a good and healthy structure, and no duplicate of information.

Maybe a good structure is:

- `benchmarks/` containing all the domain and problems. Each domain set in its own folder, with the domain file and lots of problem files.
- `planners/` containing set of planners
- `results/` containing results of experiments. Each experiment will be a folder with given name (`prp-test02`) and will have one file containing all the problem instances to be tested. When the system is ran, teh results, including output and csv stats wll go into that folder.

In the main root folder, we have the Python scripts for the system.

**Comment by lslll0302** [comment]
finished
