### ISSUE TITLE
Build a cluster planner experimental framework

### ISSUE THREAD

**Issue by ssardina** [lslll0302/Eval-of-FOND-planners-#6]
The idea will be to have a Python script that I can pass:

- A planning system (within a defined set of planners). Maybe each planner is defined in a JSAON file, with the exact command to execute
- A JSON file containing machine workers, with an IP and login and password and ssh key to use and number of CPUs that can be used in that machine.
- A result/experiment folder, as described in issue #1, where it will find a file `experiment.csv` with a list of domains to test.

The cluster will as many concurrent planning tests on the problems as possible, leaving the output of each run in the result folder and statistics in a csv file for the whole run.

This has to be done in Python and in a clean way so that I can be provided as contribution of the thesis to the community.

The architecture and code can be extracted out from the monster system to do pacman runs in a cluster:

https://github.com/AI4EDUC/pacman-contest-cluster

This system is complex, but it can be simplfiied to just what we need for planning testing

**Comment by lslll0302** [comment]
finished
