### ISSUE TITLE
Make planner a general class

### ISSUE THREAD

**Issue by ssardina** [lslll0302/Eval-of-FOND-planners-#8]
Instead of hard-coding each available planner in the code, make a generic class `Planner` that has all the info about a planner, including th command to run, and how to process the output to filter only the useful content.

Then a specific planner (e.g., PRP) will be a sub-class of `Planner`.

**Comment by lslll0302** [comment]
finished

**Comment by ssardina** [comment]
Good, we discussed this. We have the general planner class but we now need the system to work with subclasses of that class directly, without going via json files. Reopening it.

**Comment by lslll0302** [comment]
finished prp and sat
